package report

// AgentStat 代理商数据
type AgentStat struct {
	// DateTime 数据日期，格式：YYYY-MM-DD
	DateTime string `json:"date_time,omitempty"`
	// AccountID 广告主ID
	AccountID uint64 `json:"account_id,omitempty"`
	// UserID 快手id
	UserID uint64 `json:"user_id,omitempty"`
	// AccountName 广告主名称
	AccountName string `json:"account_name,omitempty"`
	// TotalChargedInYuan 总消耗（元）
	TotalChargedInYuan int64 `json:"total_charged_in_yuan,omitempty"`
	// TotalBalanceInYuan 总余额（元）
	TotalBalanceInYuan int64 `json:"total_balance_in_yuan,omitempty"`
	// RealChargedInYuan 现金消耗（元）
	RealChargedInYuan int64 `json:"real_charged_in_yuan,omitempty"`
	// TotalRebateRechargedInYuan 返点消耗（元）
	TotalRebateRechargedInYuan int64 `json:"total_real_recharged_in_yuan,omitempty"`
	// ContractRebateRealChargedInYuan 框返消耗（元）
	ContractRebateRealChargedInYuan int64 `json:"contract_rebate_real_recharged_in_yuan,omitempty"`
	// DirectRebateRealChargedInYuan 激励消耗（元）
	DirectRebateRealChargedInYuan int64 `json:"direct_rebate_real_charged_in_yuan,omitempty"`
	// CreditRealChargedInYuan 信用消耗（元）
	CreditRealChargedInYuan int64 `json:"credit_real_charged_in_yuan,omitempty"`
	// ChargeDayOnDayPercent 消耗环比
	ChargeDayOnDayPercent string `json:"charge_day_on_day_percent,omitempty"`
	// AdPhotoImpression 封面曝光数
	AdPhotoImpression int64 `json:"ad_photo_impression,omitempty"`
	// AdPhotoClick 封面点击数
	AdPhotoClick int64 `json:"ad_photo_click,omitempty"`
	// AdItemClick 行为数
	AdItemClick int64 `json:"ad_item_click,omitempty"`
	// PhotoClickRatio 封面点击率
	PhotoClickRatio string `json:"photo_click_ratio,omitempty"`
	// ItemClickRatio 行为点击率
	ItemClickRatio string `json:"item_click_ratio,omitempty"`
	// ChargedCampaignCount 有消费计划数
	ChargedCampaignCount int64 `json:"charged_campaign_count,omitempty"`
	// ProductName 产品名
	ProductName string `json:"product_name,omitempty"`
	// CorporationName 企业名称
	CorporationName string `json:"corporation_name,omitempty"`
	// FirstCostDay 首次消耗日期
	FirstCostDay int64 `json:"first_cost_day,omitempty"`
	// Industry 一级行业
	Industry string `json:"industry,omitempty"`
	// SecondIndustry 二级行业
	SecondIndustry string `json:"second_industry,omitempty"`
}
