package report

type Stat struct {
	CampaignID                       int64   `json:"campaign_id,omitempty"`                           // 广告计划ID
	CampaignName                     string  `json:"campaign_name,omitempty"`                         // 广告计划名称
	UnitID                           int64   `json:"unit_id,omitempty"`                               // 广告组ID
	UnitName                         string  `json:"unit_name,omitempty"`                             // 广告组名称
	CreativeID                       int64   `json:"creative_id,omitempty"`                           // 广告创意ID
	CreativeName                     string  `json:"creative_name,omitempty"`                         // 广告创意名称
	PhotoID                          int64   `json:"photo_id,omitempty"`                              // 视频id
	PhotoUrl                         string  `json:"photo_url,omitempty"`                             // 视频链接
	ImageToken                       string  `json:"image_token,omitempty"`                           // 封面id
	CoverUrl                         string  `json:"cover_url,omitempty"`                             // 封面链接
	Description                      string  `json:"description,omitempty"`                           // 作品广告语
	StickyUrl                        string  `json:"sticky_url,omitempty"`                            // 便利贴url地址（便利贴报表时返回）
	ImageUrls                        string  `json:"image_urls,omitempty"`                            // 图片url地址（图片报表时返回）
	AdScene                          string  `json:"ad_scene,omitempty"`                              // 广告投放场景
	Province                         string  `json:"province,omitempty"`                              // 省份
	City                             string  `json:"city,omitempty"`                                  // 城市
	Gender                           string  `json:"gender,omitempty"`                                // 性别
	AgeSegment                       string  `json:"age_segment,omitempty"`                           // 年龄
	Client                           string  `json:"client,omitempty"`                                // 系统
	BusinessInterestTags             string  `json:"business_interest_tags,omitempty"`                // 商业兴趣
	Status                           int     `json:"status,omitempty"`                                // 1 - 投放中；2 - 已暂停；3 - 已删除
	StatDate                         string  `json:"stat_date,omitempty"`                             // 数据日期，格式：YYYY-MM-DD
	StatHour                         int     `json:"stat_hour,omitempty"`                             // 数据小时
	Charge                           float64 `json:"charge,omitempty"`                                // 花费（元）
	Show                             int64   `json:"show,omitempty"`                                  // 封面曝光数
	PhotoClick                       int64   `json:"photo_click,omitempty"`                           // 封面点击数
	Aclick                           int64   `json:"aclick,omitempty"`                                // 素材曝光数
	Bclick                           int64   `json:"bclick,omitempty"`                                // 行为数
	PhotoClickRatio                  float64 `json:"photo_click_ratio,omitempty"`                     // 封面点击率
	Play3sRatio                      float64 `json:"play_3s_ratio,omitempty"`                         // 3s播放率
	ActionRatio                      float64 `json:"action_ratio,omitempty"`                          // 行为率
	Impression1kCost                 float64 `json:"impression_1k_cost,omitempty"`                    // 平均千次曝光花费（元）
	PhotoClickCost                   float64 `json:"photo_click_cost,omitempty"`                      // 平均点击单价（元）
	ActionCost                       float64 `json:"action_cost,omitempty"`                           // 平均行为单价（元）
	Share                            int64   `json:"share,omitempty"`                                 // 分享数
	Comment                          int64   `json:"comment,omitempty"`                               // 评论数
	Like                             int64   `json:"like,omitempty"`                                  // 点赞数
	Follow                           int64   `json:"follow,omitempty"`                                // 新增关注数
	CancelFollow                     int64   `json:"cancel_follow,omitempty"`                         // 取消关注数
	Report                           int64   `json:"report,omitempty"`                                // 举报数
	Block                            int64   `json:"block,omitempty"`                                 // 拉黑数
	Negative                         int64   `json:"negative,omitempty"`                              // 减少此类作品数
	Submit                           int64   `json:"submit,omitempty"`                                // 提交按钮点击数（历史字段，同下方“表单提交数”，预计年底删除该字段）
	DownloadStarted                  int64   `json:"download_started,omitempty"`                      // 应用下载数据-安卓下载开始数
	DownloadCompleted                int64   `json:"download_completed,omitempty"`                    // 应用下载数据-安卓下载完成数
	Activation                       int64   `json:"activation,omitempty"`                            // 应用下载数据-激活数
	EventPayFirstDay                 int64   `json:"event_pay_first_day,omitempty"`                   // 应用下载数据-首日付费次数
	EventPayPurchaseAmountFirstDay   float64 `json:"event_pay_purchase_amount_first_day,omitempty"`   // 应用下载数据-首日付费金额
	EventPayFirstDayRoi              float64 `json:"event_pay_first_day_roi,omitempty"`               // 应用下载数据-首日ROI
	EventPay                         int64   `json:"event_pay,omitempty"`                             // 应用下载数据-付费次数
	EventPayPurchaseAmount           float64 `json:"event_pay_purchase_amount,omitempty"`             // 应用下载数据-付费金额
	EventPayRoi                      float64 `json:"event_pay_roi,omitempty"`                         // 应用下载数据-ROI
	EventRegister                    int64   `json:"event_register,omitempty"`                        // 应用下载数据-注册数
	EventRegisterCost                float64 `json:"event_register_cost,omitempty"`                   // 应用下载数据-注册成本
	EventRegisterRatio               float64 `json:"event_register_ratio,omitempty"`                  // 应用下载数据-注册率
	EventJinJianApp                  int64   `json:"event_jin_jian_app,omitempty"`                    // 应用下载数据-完件数
	EventJinJianAppCost              float64 `json:"event_jin_jian_app_cost,omitempty"`               // 应用下载数据-完件成本
	EventCreditGrantApp              int64   `json:"event_credit_grant_app,omitempty"`                // 应用下载数据-授信数
	EventCreditGrantAppCost          float64 `json:"event_credit_grant_app_cost,omitempty"`           // 应用下载数据-授信成本
	EventCreditGrantAppRatio         float64 `json:"event_credit_grant_app_ratio,omitempty"`          // 应用下载数据-授信率
	EventOrderPaid                   int64   `json:"event_order_paid,omitempty"`                      // 应用下载数据-付款成功数
	EventOrderPaidPurchaseAmount     float64 `json:"event_order_paid_purchase_amount,omitempty"`      // 应用下载数据-付款成功金额
	EventOrderPaidCost               float64 `json:"event_order_paid_cost,omitempty"`                 // 应用下载数据-单次付款成本
	EventNextDayStay                 int64   `json:"event_next_day_stay,omitempty"`                   // 应用下载数据-次留数（仅支持分日查询）
	EventNextDayStayCost             float64 `json:"event_next_day_stay_cost,omitempty"`              // 应用下载数据-次留成本（仅支持分日查询）
	EventNextDayStayRatio            float64 `json:"event_next_day_stay_ratio,omitempty"`             // 应用下载数据-次留率（仅支持分日查询）
	FormCount                        int64   `json:"form_count,omitempty"`                            // 落地页数据-表单提交数
	FormCost                         float64 `json:"form_cost,omitempty"`                             // 落地页数据-表单提交单价
	FormActionRatio                  float64 `json:"form_action_ratio,omitempty"`                     // 落地页数据-表单提交点击率
	EventJinJianLandingPage          int64   `json:"event_jin_jian_landing_page,omitempty"`           // 落地页数据-落地页完件数
	EventJinJianLandingPageCost      float64 `json:"event_jin_jian_landing_page_cost,omitempty"`      // 落地页数据-落地页完件成本
	EventCreditGrantLandingPage      int64   `json:"event_credit_grant_landing_page,omitempty"`       // 落地页数据-落地页授信数
	EventCreditGrantLandingPageCost  float64 `json:"event_credit_grant_landing_page_cost,omitempty"`  // 落地页数据-落地页授信成本
	EventCreditGrantLandingPageRatio float64 `json:"event_credit_grant_landing_page_ratio,omitempty"` // 落地页数据-落地页授信率
	EventValidClues                  int64   `json:"event_valid_clues,omitempty"`                     // 落地页数据-有效线索数
	EventValidCluesCost              float64 `json:"event_valid_clues_cost,omitempty"`                // 落地页数据-有效线索成本
	AdProductCnt                     int64   `json:"ad_product_cnt,omitempty"`                        // 商品成交数
	EventGoodsView                   int64   `json:"event_goods_view,omitempty"`                      // 商品访问数
	MerchantRecoFans                 int64   `json:"merchant_reco_fans,omitempty"`                    // 涨粉量
	EventOrderAmountRoi              float64 `json:"event_order_amount_roi,omitempty"`                // 涨粉量
	EventGoodsViewCost               float64 `json:"event_goods_view_cost,omitempty"`                 // 商品访问成本
	MerchantRecoFansCost             float64 `json:"merchant_reco_fans_cost,omitempty"`               // 涨粉成本
	EventNewUserPay                  int64   `json:"event_new_user_pay,omitempty"`                    // 新增付费人数
	EventNewUserPayCost              float64 `json:"event_new_user_pay_cost,omitempty"`               // 新增付费人数成本：当日消耗 / 当日新增付费人数
	EventNewUserPayRatio             float64 `json:"event_new_user_pay_ratio,omitempty"`              // 新增付费人数率：当日新增付费人数 / 当日行为数
	EventButtonClick                 int64   `json:"event_button_click,omitempty"`                    // 按钮点击数
	EventButtonClickCost             float64 `json:"event_button_click_cost,omitempty"`               // 按钮点击成本：当日消耗 / 按钮点击数
	EventButtonClickRatio            float64 `json:"event_button_click_ratio,omitempty"`              // 按钮点击成本：当日消耗 / 按钮点击数
	Play5sRatio                      float64 `json:"play_5s_ratio,omitempty"`                         // 5s播放率
	PlanEndRatio                     float64 `json:"play_end_ratio,omitempty"`                        // 完播率
	EventOrderPaidRoi                float64 `json:"event_order_paid_roi,omitempty"`                  // 订单支付率：订单支付数/商品访问数
	EventNewUserJinjianApp           int64   `json:"event_new_user_jinjian_app,omitempty"`            // 新增完件人数
	EventNewUserJinjianAppCost       float64 `json:"event_new_user_jinjian_app_cost,omitempty"`       // 新增完件人数成本：消耗/新增完件人数
	EventNewUserJinjianAppRoi        float64 `json:"event_new_user_jinjian_app_roi,omitempty"`        // 新增完件人数率：新增完件人数/（转化+表单提交）
	EventNewUserCreditGrantApp       int64   `json:"event_new_user_credit_grant_app,omitempty"`       // 新增授信人数
	EventNewUserCreditGrantAppCost   float64 `json:"event_new_user_credit_grant_app_cost,omitempty"`  // 新增授信人数成本：消耗/新增授信人数
	EventNewUserCreditGrantAppRoi    float64 `json:"event_new_user_credit_grant_app_roi,omitempty"`   // 新增授信人数率：新增授信人数/（转化+表单提交）
	EventNewUserJinjianPage          int64   `json:"event_new_user_jinjian_page,omitempty"`           // 落地页新增完件人数
	EventNewUserJinjianPageCost      float64 `json:"event_new_user_jinjian_page_cost,omitempty"`      // 落地页新增完件人数成本
	EventNewUserJinjianPageRoi       float64 `json:"event_new_user_jinjian_page_roi,omitempty"`       // 落地页新增完件人数率
	EventNewUserCreditGrantPage      int64   `json:"event_new_user_credit_grant_page,omitempty"`      // 落地页新增授信人数
	EventNewUserCreditGrantPageCost  float64 `json:"event_new_user_credit_grant_page_cost,omitempty"` // 落地页新增授信人数成本
	EventNewUserCreditGrantPageRoi   float64 `json:"event_new_user_credit_grant_page_roi,omitempty"`  // 落地页新增授信人数率
	EventAddWechat                   int64   `json:"event_add_wechat,omitempty"`                      // 微信复制数
	EventAddWechatCost               float64 `json:"event_add_wechat_cost,omitempty"`                 // 微信复制成本
	EventAddWechatRatio              float64 `json:"event_add_wechat_ratio,omitempty"`                // 微信复制率
	EventGetThrough                  int64   `json:"event_get_through,omitempty"`                     // 智能电话-确认接通数
	EventGetThroughCost              float64 `json:"event_get_through_cost,omitempty"`                // 智能电话-确认接通成本
	EventGetThroughRatio             float64 `json:"event_get_through_ratio,omitempty"`               // 智能电话-确认接通率
}
